### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by PROGRAMMINGENGINEER-NIKI** [leomariga/StackOverflowSolutions#3]
@ Leonardo Mariga, Is this equation "dst(x,y)=..." a mathematical equation? if not, could you please provide the mathematical equation for this transformation? I need to read more about the mathematics behind it. Thanks
I put equation in this link
(https://ibb.co/DGCbTdt)

referred question
https://stackoverflow.com/questions/57399915/how-do-i-determine-the-locations-of-the-points-after-perspective-transform-in-t

**Comment by leomariga** [comment]
It is a mathematical transformation. You can think this as a function if you want. Just use a set of points as input and you will get another set of point as output.
